// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface MarathonTrainingTestFormService {
    Tests: Test[];
}

export interface Test {
    Title:   string;
    English: English;
    Spanish: Spanish;
}

export interface English {
    Questions: Question[];
}

export interface Spanish {
    Questions: Question[];
}

export interface Question {
    Text:    string;
    Answers: Answer[];
}

export interface Answer {
    Letter:     string;
    AnswerText: string;
    IsCorrect:  boolean;
}
